import base64
import os
from datetime import timedelta

TWITCH_EXTENSION_SECRET = base64.b64decode(os.environ['TWITCH_EXTENSION_SECRET'])
TWITCH_EXTENSION_CLIENT_ID = os.environ['TWITCH_EXTENSION_CLIENT_ID']
TWITCH_EXTENSION_VERSION = os.environ['TWITCH_EXTENSION_VERSION']
TWITCH_EXTENSION_OWNER_ID = os.environ['TWITCH_EXTENSION_OWNER_ID']
API_HOSTNAME = os.environ['API_HOSTNAME']
IMGPROXY_PROTOCOL = os.environ['IMGPROXY_PROTOCOL']
IMGPROXY_HOSTNAME = os.environ['IMGPROXY_HOSTNAME']
IMGPROXY_KEY = os.environ['IMGPROXY_KEY']
IMGPROXY_SALT = os.environ['IMGPROXY_SALT']

CACHED_DCCON_UPDATE_DELTA = timedelta(hours=1)
