"""empty message

Revision ID: 764318a66b40
Revises: 4e4ec00a0781
Create Date: 2018-01-04 14:45:28.437049

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '764318a66b40'
down_revision = '4e4ec00a0781'
branch_labels = None
depends_on = None


def upgrade():
    op.rename_table('setting', 'channel')
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel', sa.Column('cached_dccon', sa.JSON(), nullable=True))
    op.add_column('channel', sa.Column('is_using_cache', sa.Boolean(), nullable=True))
    op.execute('UPDATE channel SET is_using_cache = FALSE')
    op.alter_column('channel', 'is_using_cache', nullable=False)
    op.add_column('channel', sa.Column('last_cache_update', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channel', 'last_cache_update')
    op.drop_column('channel', 'is_using_cache')
    op.drop_column('channel', 'cached_dccon')
    # ### end Alembic commands ###
    op.rename_table('channel', 'setting')
