"""empty message

Revision ID: 9059e4af68df
Revises: 764318a66b40
Create Date: 2018-01-13 07:20:58.949901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9059e4af68df'
down_revision = '764318a66b40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel', sa.Column('dccon_type', sa.Unicode(length=32), nullable=True))
    op.execute('UPDATE channel SET dccon_type = \'open_dccon\'')
    op.alter_column('channel', 'dccon_type', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channel', 'dccon_type')
    # ### end Alembic commands ###
